In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv('variables.csv')

In [4]:
data

,Taluka,Ratio of allocation,Ratio of distribution,Public distribution Ratio,Storage Ratio,Road Density,Population density per FPSs,% GIS enabled FPSs,% of EPOS availability,Online Payment facility,Data availability on portal,% of complaint resolved,% of staff available,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,Dahanu,0.98,0.79,94.31,7246.38,32.08,1.82,46.86,92.27,0.0,1.0,85.00,69.23,NaN,NaN,NaN,NaN,NaN,NaN
1,Jawhar,0.95,0.91,256.42,8854.17,45.99,2.18,97.92,94.79,0.0,1.0,100.00,75.00,NaN,NaN,NaN,NaN,NaN,NaN
2,Mokhada,1.06,0.83,4277.34,11718.75,37.13,2.47,1.56,95.31,0.0,1.0,75.00,57.14,NaN,NaN,NaN,NaN,NaN,NaN
3,Palghar,0.94,0.78,125.31,7990.87,19.40,2.33,33.33,97.72,0.0,1.0,78.46,92.86,NaN,NaN,NaN,NaN,NaN,NaN
4,Talasari,1.05,0.90,1450.12,10869.57,53.20,7.76,0.00,94.20,0.0,1.0,100.00,66.67,NaN,NaN,NaN,NaN,NaN,NaN
5,Vasai,1.03,0.72,367.10,11111.11,250.52,12.73,43.89,100.00,0.0,1.0,96.04,53.85,NaN,NaN,NaN,NaN,NaN,NaN
6,Vikramgad,0.93,0.87,385.09,3804.35,48.80,2.76,17.39,89.13,0.0,1.0,26.67,0.00,NaN,NaN,NaN,NaN,NaN,NaN
7,Wada,0.93,0.81,180.81,9554.14,44.67,1.38,45.22,78.34,0.0,1.0,48.00,60.00,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 19 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Taluka                       8 non-null      object
 1   Ratio of allocation          8 non-null      float64
 2   Ratio of distribution        8 non-null      float64
 3   Public distribution Ratio    8 non-null      float64
 4   Storage Ratio                8 non-null      float64
 5   Road Density                 8 non-null      float64
 6   Population density per FPSs  8 non-null      float64
 7   % GIS enabled FPSs           8 non-null      float64
 8   % of EPOS availability       8 non-null      float64
 9   Online Payment facility      8 non-null      float64
 10  Data availability on portal  8 non-null      float64
 11  % of complaint resolved      8 non-null      float64
 12  % of staff available         8 non-null      float64
 13  Unnamed: 13                  0 non-null      float64
 14  Unnamed: 14                  0 non-null      float64
 15  Unnamed: 15                  0 non-null      float64
 16  Unnamed: 16                  0 non-null      float64
 17  Unnamed: 17                  0 non-null      float64
 18  Unnamed: 18                  0 non-null      float64
dtypes: float64(18), object(1)
memory usage: 1.3+ KB

In [6]:
data  = data.iloc[:,:-6]

In [7]:
del data["Online Payment facility"]
del data["Data availability on portal"]

In [8]:
data.describe()

,Ratio of allocation,Ratio of distribution,Public distribution Ratio,Storage Ratio,Road Density,Population density per FPSs,% GIS enabled FPSs,% of EPOS availability,% of complaint resolved,% of staff available
count,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000
mean,0.983750,0.826250,892.062500,8893.667500,66.473750,4.178750,35.771250,92.720000,76.146250,59.343750
std,0.055016,0.064794,1436.184361,2582.077488,75.134629,3.994487,31.474349,6.666085,26.346404,26.931177
min,0.930000,0.720000,94.310000,3804.350000,19.400000,1.380000,0.000000,78.340000,26.670000,0.000000
25%,0.937500,0.787500,166.935000,7804.747500,35.867500,2.090000,13.432500,91.485000,68.250000,56.317500
50%,0.965000,0.820000,311.760000,9204.155000,45.330000,2.400000,38.610000,94.495000,81.730000,63.335000
75%,1.035000,0.877500,651.347500,10929.955000,49.900000,4.010000,45.630000,95.912500,97.030000,70.672500
max,1.060000,0.910000,4277.340000,11718.750000,250.520000,12.730000,97.920000,100.000000,100.000000,92.860000